export const POSTS_REQUEST = 'POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';

export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WIDOW = 'CLOSE_MODAL_WINDOW';