export const POSTS_REQUEST = 'POSTS_REQUEST';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const AUTHORIZATION_REQUEST = 'AUTHORIZATION_REQUEST';
export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const SIGN_OUT = 'SIGN_OUT';

export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WIDOW = 'CLOSE_MODAL_WINDOW';

export const UNKNOWN_ERROR = "unknown error";